#!/usr/bin/env python2.7

"""
Script used to compare observed and synthetic profiles generated 
by SynthPro.

"""


from synthpro.synthpro import *


def get_args():
    """
    Get arguments from command line.
    
    """
    parser = argparse.ArgumentParser(
        description='Compare observed and synthetic profiles generated by SynthPro')
    parser.add_argument(
        'month', type=int, help='Month used in file names.')
    parser.add_argument(
        'year', type=int, help='Year used in file names.')
    parser.add_argument(
        'namelist', type=str, help='Path to namelist.ini')
    parser.add_argument(
        '-d', '--day', type=int, help='Day used in file names.', default=None)
    args = parser.parse_args()

    return args


if __name__ == '__main__':
    
    # Build paths to input data files
    args = get_args()
    config = namelist.get_namelist(args)    
    printmsg.message(config, 'Loading input data')
    config = tools.build_file_name(args, config, 'obs_profiles')
    config = tools.build_file_name(args, config, 'synth_profiles')
    config = tools.build_file_name(args, config, 'model_temp')
    config = tools.build_file_name(args, config, 'model_sal') 
    printmsg.inputs(config) 
    
